name: Code quality

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  code-quality:
    name: Checks if ts and lint works
    runs-on: macos-latest
    steps:
      - name: Check TypeScript
        run: yarn ts

      - name: Check ESLint
        run: yarn lint
